### ISSUE TITLE
IE's Coke Oven is superior to RC's coke oven for charcoal but requires treated sticks (=creosote) to make

### ISSUE THREAD

**Issue by Barhandar** [lazerous42/Ascension-of-the-Technomancer#11]
RC coke oven requires 26\*4 bricks and 26\*5 sand to make, totaling 104 clay and 130 sand, and forms automatically.  
IE coke oven requires 14\*4 clay, 14\*4 bricks, and 14\*1 sandstone (14\*4 sand if crafted) to make, totaling 112 clay and 56 sand, and forms after being hit with Engineer's Hammer, recipe for which has been changed to require treated sticks.

RC coke oven processes 1 wood into 1 charcoal and 250 mB creosote in 1800 ticks, 1 coal into 1 coke and 500 mB creosote in 1800 ticks.  
IE coke oven processes 1 wood into 1 charcoal and 250 mB creosote in 900 ticks, 1 coal into 1 coke and 500 mB creosote in 1800 ticks.

Effectively this means IE's coke oven is superior, and RC coke oven is only going to be used to get 1 bucket of creosote to craft treated sticks (provided player doesn't find creosote/treated sticks in treasure chests), then abandoned due to slowness, especially if the player needs charcoal and not creosote and doesn't use GT charcoal pile/powered furnaces yet.

**Comment by lazerous42** [comment]
Thank you for bringing this idea out of reddit so it's easier to track.  Not a bug, so thus lower priority than bugs, but this is an idea I like as a unique justification for both machines is cool.  This is probably a 5.0.x idea.

**Comment by lazerous42** [comment]
This has been implemented in version 5.0.1 (deployment still pending for further testing).  The IE coke over is demonstrably faster at 1200 ticks per operation, where as Railcraft's gives twice as much creosote (500 instead of 250)

Also, as far as I know, version 5.0.1 is complete for it's initial rollout.  I still need to give things another once over review, but I don't have anymore required items on the to do list.  Changes the size of this update are bound to have some flaws, so I need to be extra careful to try and squash as many bugs as I can before giving it the stamp of approval.
