### ISSUE TITLE
Squid, Fishy and Small Fish (Mo' Creatures for two latter) spawn in obscene quantities

### ISSUE THREAD

**Issue by Barhandar** [lazerous42/Ascension-of-the-Technomancer#15]
I've just /cofh killall'ed 277 Small Fishes and 99 Fishys, and I'm nowhere near large water bodies (though has been there recently). Suffice to say, this many 3D-moving mobs obliterates performance.

At least squid have decency to despawn as I move away from them...

**Comment by lazerous42** [comment]
Made a few tweaks to help curb their numbers.   Their spawn cap has been lowered from 10->5 and their tick spacer has been increased from 10->100.  Chunk spawning of WATERCREATURE types are now allowed at the same rate as land CREATURE type entities.  Hopefully this will make this problem less likely to occur, it's kind of hard to test since it takes a while for their numbers to really add up.  

I'm kind of making the assumption that they don't actually despawn.  This can be forced from MoC, but it's global and would affect land creatures as well.  I'd rather not do this, farm animals despawning would be really frustrating.  This should help, if not we can revisit this subject.  Also, I bumped up the max entity count from GT from 3->5.  

I am going to pack in more fixes before pushing this out to FTB, so you can grab the 4.2.2 full set of pack configs from here before they are formally deployed and just dump them in over your install (or since you seem to be rather knowledgeable about pack making stuff, you can feel free to be selective if you choose).  Should this still be problematic, we can revisit this subject

**Comment by wholesalegerbils** [comment]
I haven't noticed any issues since this change but I thought it was interesting that when I used /cofh killall in an aquatic area that was causing me *extreme* lag (~2 fps) before the change I killed something like 600 small fishies, 60 dolphins, 200 jellyfish, and 600 medium fish to a tune of ~1800 total creatures (with 1600 being aquatic).

**Comment by lazerous42** [comment]
The idea of spawn caps is kind of weird in JAS.  For the type WATERCREATURE the cap was set to 10 (compared to CREATURE at 20 and MONSTER at 60).  It doesn't specific exactly what area is being considered for the cap.  I doubt that's a per chunk value because 60 MONSTERS per chunk over all loaded chunks surrounding each player is far more than the game can reasonably handle even in a vanilla loadout.  Also, entities obviously are not locked into a single chunk so the whole concept is a bit fuzzy.  I figured halving the spawn cap would be a good start, along with increasing the number of the spawning tick interval this group is eligible to be spawned during (i.e. more spawning ticks are skipped for this group).  I don't think that these entities actually despawn, so were going to treat them more like the land bound CREATURE spawns.  Also, they are now eligible for chunk spawning (they can be spawned as a part of chunk generation like other passives).  For reference, the normal spawner loop is called "passive spawning", in case I ever use this term in the future.
