### ISSUE TITLE
new mod request

### ISSUE THREAD

**Issue by trailertrash13** [lazerous42/Ascension-of-the-Technomancer#19]
love the pack. is it possable to add another mod for scanning for ores like the one in this github thread?
https://github.com/GTNewHorizons/NewHorizons/issues/1543
the scanner with the gui would be cool

**Comment by lazerous42** [comment]
This sounds fine.  I will have to test it out to confirm that the sky doesn't implode or anything from adding more content, but it seems like a decent fit.  I really just want players to have to venture out and explore the world, endless hunting and not finding what you need isn't exactly a fun gameplay mechanic.  I MAY go with Dream-Master's philosophy of only having higher tier ones available, but until I actually see how it works I can't really say for sure.  
Right now, there will be another 4.2.x release that will just contain bug fixes.  This will be evaluated for the 5.0.x release where there will be a major content update to provide a creative solution to the problems with the new Chromaticraft biome not spawning in BIOMESOP type worlds.

**Comment by trailertrash13** [comment]
cool thank you

**Comment by lazerous42** [comment]
The GT Vein Finder has been added to the pending version 5.0.1 AotT update.  Hopefully update will be going out soon, but due to the size and scope of the changes, I need to do some substantial testing and review of all the new configs.  I don't have anything else on the development to do list though.

The two mods mentioned in the GT New Horizons thread were quite difficult to track down.  GT Vein Finder was only available from some Chinese site that kept trying to pull in some dubious download extensions for Chrome, and the other one didn't seem to have a complied version available, just the source code.  Although I do have the skills to compile it myself (I'm a professional programmer by trade, although I don't specialize in Java), that's a time sync I can't really afford with pack support and YouTube (although that mod did look pretty dame cool)

**Comment by trailertrash13** [comment]
np thanks for adding the one and looking into the other. the pack has all my fav mods but to be honest i dont care for gt ore hunting to much. so keep on and thanks
