### ISSUE TITLE
Unstable Ingot Block Not Craftable

### ISSUE THREAD

**Issue by wholesalegerbils** [lazerous42/Ascension-of-the-Technomancer#22]
Issue:  You cannot craft Unstable Ingot Blocks (I think) in the compressor per the recipe.   

I believe the issue is that when you make unstable ingots they don't stack and if you exit the crafting window they also explode.  You can perform the pseudo-inversion ritual to stabilize the ingots you make later on but the compressor only takes 9x Unstable Ingot 8782 instead of also allowing Mobius "Unstable/Stable" Ingot 8282:2.  

I believe Gregtech is more specific than most recipes as, for example, the "Portal to the Deep Dark" is not listed when looking at what you can use Mobius "Unstable/Stable" ingot 8282:2 for but still allows you to craft it.

**Comment by lazerous42** [comment]
Seems like a GT bug, as forcing the update of the compressor is something that gets done automatically for many types of blocks.  Let me see if I can override it (probably can), either way, I'll let Blood Asp and Dream Master know.

**Comment by lazerous42** [comment]
I have added a compressor recipe that involves the mobuis ingots specifically, and the unstable ingot compressor recipe should now be disabled.  I have also re-enabled the vanilla crafting using the unstable ingots.  Since the fix is currently tangled up with all the 5.0.1 stuff grabbing it early would be tricky, as it's not just a script change, there is a GregTech config change as well.  Those GT files have a bunch of 5.0.1 stuff in them, and I can't guarantee what would happen if you dropped in those files into a 4.3.9 install.  Probably be best just to wait, but you can see what file were changed by looking at the commit I made and apply that to your own install if you so choose.
