### ISSUE TITLE
[5.0.1] Checking the usage of many GT related items freezes the client

### ISSUE THREAD

**Issue by Pandemoneus** [lazerous42/Ascension-of-the-Technomancer#27]
I.e. when I press 'U' on the hammer or file, or some of the GT dusts, the client just freezes. I've waited about 2 minutes before I decided to kill the Minecraft client process.

**Comment by wholesalegerbils** [comment]
https://github.com/lazerous42/Ascension-of-the-Technomancer/issues/2

It's an interaction between Chromaticraft and Gregtech and not actually fixable save Reika or Bloodasp doing some work on it.  I've seen it pop up on both of their githubs before (or, at least, Reika's) and they gave it some time but didn't find a solution.  It only happens the first time you see (u)ses of an item with NEI each world load, and Minecraft will hang for 5-15 minutes depending on the strength of your computer.  You will get some tick lag when you return (so do it somewhere safe) but any further attemps to look at (u)ses will work just fine.  

It's pretty annoying but the only way to fix it is to cull Gregtech or Chromaticraft.  I imagine if you don't have an established world that it wouldn't be too big of a deal to get rid of Chromaticraft but the use bug is just ~5 mins of inconvenience each world load so usually it's not too obnoxious.

**Comment by Barhandar** [comment]
> I've seen it pop up on both of their githubs before (or, at least, Reika's) and they gave it some time but didn't find a solution. 

Given most recent discussions on Reika's, the next Chromaticraft update will likely change the issue.
>but the use bug is just ~5 mins of inconvenience

20x3, it doesn't process all the items first time and can trigger two more times. But yeah, basically, just wait longer.

**Comment by lazerous42** [comment]
As was mentioned above, sadly I cannot fix this.  There was supposedly a change to Chromaticraft that would fix this, but it didn't.  What happens is that Chromaticraft does some dynamic processing of the block/item recipe tables to integrate other mods content into CC.  This gets all fucked up by the fact that GregTech allows for machines to be recycled.  This causes lots of circular recipe changes and CC gets real sad about it, then players get real sad about it, then I get real sad about it.

There is unfortunately nothing I can do.  Had I known about this far earlier in the development process, it could very well have massively changed the development direction of the pack.  However, things were already deployed by the time that I learned of this problem.

All you need to reproduce this problem is CC, GT, and NEI, and you will hit this nasty hangup.  Fortunately, it only affects "U"sage, and not "R"ecipes, so you can still play through the content (I know it still sucks pretty bad though).  You can read more about it here if your curious..

https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/668
