### ISSUE TITLE
Orechid generates Asteroid Certus Quartz ore, which drops disabled item from AE2

### ISSUE THREAD

**Issue by Barhandar** [lazerous42/Ascension-of-the-Technomancer#30]
Orechid gets its list of ores to generate from OreDictionary, so if `<InterstellarOres:oreAsteroid:2>` and `<InterstellarOres:oreIce:2>` get `<ore:oreCertusQuartz>` entry removed, it will generate something else - hopefully less broken.

I guess this is caused by Interstellar Ores ignoring that GregTech overrides Certus Quartz, and continuing to try and spawn AE2's disabled version of it.

**Comment by Barhandar** [comment]
Correction: pretty sure Interstellar Ores shouldn't exist in the pack anymore due to removing GalactiCraft, but the issue with Orechid can appear with other ores as well.

Also, orechid cannot generate GregTech ores due to them being TEs. For GT [you need a separate mod implementing compatibility](https://mods.curse.com/mc-mods/minecraft/263540-gregtania).

**Comment by lazerous42** [comment]
Yes, this should now be completely impossible due to the fact that Interstellar Ores / Galacticraft is gone.  I already knew about the GT non-ticking tile entity ores generally not playing nice with a large variety of other mods/machines.  I didn't know there was a solution for the orechid though.  I'm going to test that out right now.

**Comment by lazerous42** [comment]
Gregtania has been added.  The multi-tiered approach has been disabled.  Only the best variants are available and they are expensive.  Loot tables have been update accordingly (Orechids are a chest loot item).

Thank you for the info about this mod.  It will be in 5.1.x
