### ISSUE TITLE
Some AoA dimensions are unreachable via the Ancient Teleporter

### ISSUE THREAD

**Issue by LosGrak** [lazerous42/Ascension-of-the-Technomancer#32]
Simply a recap of our discussion on Reddit:

**From LosGrak**: Using the Ancient Teleporter, I'm unable to reach the below as they cause the game to "Download Terrain" forever: Deeplands, L'Borean, Dustopia, and Creeponia. Tested multiple times through many configurations of settings.

**From Lazerous42**: Solution found. GregTech is getting pissy trying to put ores in worlds that have no valid replaceable blocks. When I reproduced the problem, I noticed that I suddenly had diffs in my GregTech/WorldGeneration.cfg. Specifically, I noticed the following line added to every ore vein in the dimensions section.
B:DimensionBorean_true=true
This line means that the default for this dimension is true, changing it to
B:DimensionBorean_true=false
Stops the issue. It seems like it totally freaks out when it never succeeds to find blocks it can replace with ore. The console output indicated that Chromaticraft was involved in the infinite oregen recursion, but that could just be a red herring as CC embeds itself in every inch of the games core logic.

**Comment by lazerous42** [comment]
As documented above, this problem was coming from GregTech trying to generate ore in worlds that lack any stone, endstone, or netherrack.  This seemed to piss it off royally, causing it to infinitely generate chunks on initial load of the dimension.  Eventually, internal data structures blew out their size limits and the server would crash although the client would not, leaving your session hanging forever.  

This was corrected by manually setting records for each GregTech small ore and composite vein for each dimension in the pack.  All GT ores were disabled for all AoA dimensions and the problem was solved.  As a part of this, the GregTech\WorldGeneration.cfg file was entirely regenerated to cleanup old and unused records.  All customization were then merged back into the fresh file.  

This change is available in version 5.1.1 configs.  GregTech was updated in AotT 5.1.0 (unreleased).  So to minimize the risk of conflicts, I would recommend just pulling the following file and dropping it into your existing instance.  

/config/GregTech/WorldGeneration.cfg

I will be adding a few additional fixes to 5.1.1 tonight and then sending it out for deployment.  There isn't going to be a long hangup for this release like 5.0.1.
