### ISSUE TITLE
Forests on the Moon?

### ISSUE THREAD

**Issue by LosGrak** [lazerous42/Ascension-of-the-Technomancer#33]
Screenshot pretty much says it all. Is this by design?

First time I've gone to the Moon in my test world. Version 5.1.2. The forest biomes are causing all kinds of creatures to spawn, but since there is no air they just suffocate. However, since enemies are being spawned and killed so fast, and in such large numbers, it causes the game to crash. Placing the game into Peaceful did not seem to fix that issue.

![2017-10-02_23 23 16](https://user-images.githubusercontent.com/32402873/31108714-ed3ba294-a7c8-11e7-9db2-91750181108d.png)

**Comment by lazerous42** [comment]
Well, fuck.  It's the 128 sub-biome bug.    I thought I rendered this impossible by choice of biome slot selection.  I need to think about this.

**Comment by lazerous42** [comment]
Good lord this bug (128 sub-biome bug) has driven me nuts over the last 2 years.  So if your not familiar with this issue.  Minecraft assumes that if any given biome has sub-biomes , they will always be found in that biomes ID+128.  This causes no end of headaches for large packs as it's quite difficult to work around it (DragonAPI has blocked this from happening in the overworld, in addition to the creative way I originally set up the IDs) .  
So although objects setup as Moon type bodies are restricted to only have the one Moon biome, becase dense forest was moon+128 this is the results.  I fond a place to store the moon biome in the upper set opposite to the sky  (end) biome, so there shouldn't be any places with inappropriate moon biomes as a result of this change.
So next, how it gets fixed.  You should be able to just dump in the update files and your save will be fixed.  I have included the notes about how pushing out star map changes works below.  This text is now at the head of the read me, and the process is also described in the in-game guide.

_NOTICE: The Version 5.2.0 corrects an instance of the 128+ sub-biome bug.  The moon (was biome 40) was causing dense forests (biome 168) to have the chance to generation on planet's moons.  This was corrected by choosing a biome ID for the moon that doesn't exhibit the sub-biome bug (137), and setting the flag B:resetPlanetsFromXML=true in ..\config\advRocketry\AdvancedRocketry.cfg.  This will push out the update star map with the fix into your world save.  If you lanch the game without loading into the affected world, this flag will reset itself.  You will need to close out the game and reset the flag back to true before loading into your world to get the changes to take effect.  What is happening is the master copy of planetDefs.xml from the AR configs are being copied into the world being loaded.  You need the corrected master copy of planetDefs.xml to be copied into your world to fix the problem.  You also should delete any affected AR dimensions in ..\saves\[world_name]\AdvRocketry\DIM-ID so that they will be regenerated from scratch with the update planetDefs.xml.  MCEdit can also be used for this purpose if a less invasive edit is needed._

The update pack will be sent off for posting as soon as uploading finishes by tomorrow morning.  In the mean time, you can just copy in the update files to address this.  Spread the word if any other reports come in that I don't see before the deployment.  Thank you.
