### ISSUE TITLE
Suddenly crashing only a few minutes into gameplay and I don't know why

### ISSUE THREAD

**Issue by LosGrak** [lazerous42/Ascension-of-the-Technomancer#36]
First, let me preface by saying that I have not yet made any of the changes that will be upcoming in the 5.2.0 push. I have decided to revert back to an earlier save where I have not yet gone to Luna and encountered the sub-128 biome bug there. So I am still at the Overworld dimension and just standing at my AR testing area. This save worked just fine after the update to 5.1.2, but now I have no idea why it's crashing after only a few minutes. Attached is the crash report. I am using all of the recommended settings for memory and Java arguments.

[crash-2017-10-05_00.07.35-client.txt](https://github.com/lazerous42/Ascension-of-the-Technomancer/files/1358018/crash-2017-10-05_00.07.35-client.txt)

**Comment by LosGrak** [comment]
I'm gonna close this issue. It appears to be something within my MultiMC instance that is causing it. I was able to load and run my saves with no problem within the Twitch Launcher instance of AotT. Hopefully recreating the instance in MultiMC will fix it.

**Comment by lazerous42** [comment]
I did a little research to see if I can find the origin of this, be everything seems to lead back to Optifine and not Advanced Rocketry.  I know that using a higher than OptiFine_1.7.10_HD_U_D6 causes problems, but I don't remember if this is the manifestation of it.  I do run using MultiMC and that version of Optifine so that alone doesn't explain it.  Glad you found a work around, although MultiMC is the best ;launcher.  I'll make a note of this and see if I can find an source for this.
