### ISSUE TITLE
Please stop committing irrelevantly changed config files (everything which autoupdates a timestamp/clientID) to repository

### ISSUE THREAD

**Issue by Barhandar** [lazerous42/Ascension-of-the-Technomancer#37]
It makes commits _really_ annoying to check for actual changes.

I also mean files like: AntiIDConflict's scannerfiles, debug logs, Loot++ scannerfiles, etc, everything which doesn't affect client-server behavior or is purely output.

**Comment by lazerous42** [comment]
Ya, sorry I'm not really a fan of mods doing this either.  I'll try and filter them out.  I'm trying to do the best I can for free so that people can have a good time,  I apologize that it's not good enough.  I don't want to inadvertently loose important changes so I just commit the entire folder.  I will try adjust my workflow to your liking.
