### ISSUE TITLE
Impossible to obtain Thaumcraft's thaumium block legitimately?

### ISSUE THREAD

**Issue by Not-February** [lazerous42/Ascension-of-the-Technomancer#4]
Compressing nine thaumium ingots in a compressor yields a Gregtech thaumium block, which cannot be used in any recipes that call for Thaumcraft's innate version(such as the magician's blood orb, for example, and I don't think it would work for other Thaumcraft recipes either, I know some addons make use of it at least), even though they appear to be ore dictionary'd to each other according to the tooltips.

I tried making a Forge Lexicon to transform it, but the ore dictionary entry for the block of thaumium doesn't show up at all, even though the ingots and nuggets do.

I also waited a while to see if it would auto-transform like Thaumcraft's elemental shards do when you pick them up after mining them, but it isn't doing that, and it's been much longer than it would normally take for other items to auto-"correct" into the unified versions.

Additionally there appears to be no actual recipe for Thaumcraft's thaumium block in NEI except by chiseling an existing one that's in another pattern, so making it the normal way(i.e. crafting 9 ingots in a grid) is out, since that's been scrapped in favor of the compressor - which, as I mentioned, is what I tried first.

I'm playing on a private server and I happen to be the owner of said server, so I can just cheat in the equivalent block as a trade-off without issue, but I thought you might like to know that issues were had regarding blocks of thaumium in case it happens to others as well.

I _have_ modified the modpack ever-so-slightly , but none of the mods I added would impact crafting or the scripts from MT in any way(they're generally cosmetic, like SkinPort, or TNT Utilities to prevent TNT usage in-world, and.... that's all I really did to it actually).

**Comment by wholesalegerbils** [comment]
This is fixed in version 3.8.3 -- Lazarus said that he was going to update the modpack in a few days on curse/ftb but wanted to get a few mod updates in first.  3.8.3's config files are already available via the live repository on githubwith the proposed fix (it fixes Ars Magica 2's blue topaz block as well).

**Comment by lazerous42** [comment]
It should be available on curse now.  There was some kind of cross posting issue between FTB and Curse/Twitch (It's actually an FTB hosted pack, just mirrored on Curse).  I always post the updated configs here at the same time as I post the distributables for FTB so that people don't have to wait.  If your running 3.8.3+ then you can re-open and I'll check into it.
