### ISSUE TITLE
Dungeon Mobs ignore mobGriefing gamerule and in general are terribly designed

### ISSUE THREAD

**Issue by Barhandar** [lazerous42/Ascension-of-the-Technomancer#40]
Umber Hulk has no delay on attacks whatsoever, high-speed blendering the player.  
Destrachan spams ranged block-breaking explosions whenever player is nearby.  
Cave Fisher covers everything next to them in persistent cobwebs.  
Shrieker spams non-directional shriek whenever player is nearby, which not only aggravates player directly and has chances to cause issues, but also reverses movement controls half the time with "Confusion" debuff.  
Rust Monster doesn't actually care whether the armor is metal, happily obliterating leather.

**Comment by wholesalegerbils** [comment]
The Dungeon Mobs mod is definitely a mess of a mod.  I like some of the difficulty but the enemies themselves are frequently pretty obnoxious.  The cave fisher alone will result in entire chunks being blanketed in cobwebs (and will just throw them at you while you're flying and, as far as I can tell, autohit you with them).  The Vescavor might be the most annoying creature ever created and kill every headphone user that comes near it.  

I think the issue is the mod is attempting to emulate DND/Pathfinder-style monsters but it just doesn't work for Minecraft.  There are no "saving throws" in Minecraft so the Vescavor just stacks confusion on you forever.

**Comment by lazerous42** [comment]
You can just pull it out, it will be formally removed in the next release that I will be cutting tonight or tomorrow.  I would like to find a replacement to add some challenge to the Twilight and Aether, but life has grown quite difficult as of late (hence my absence here and the lack of new episodes on Youtube) and I don't think I will be able to locate and configure a replacement as building spawn lists is very time consuming.
