### ISSUE TITLE
Iron Door Recipe Bug

### ISSUE THREAD

**Issue by wholesalegerbils** [lazerous42/Ascension-of-the-Technomancer#6]
The iron door, when crafted via shaped crafting, gives a yield of 3 iron doors for 6 plates and a little durability from your hammer.  Doing it the Gregtech way via the assembler only yields 1 iron door for 6 plates.  You can put a single iron door in an induction smelter with sand for a total of a 12 ingot gain + 25% chance of slag.

**Comment by lazerous42** [comment]
Interesting, I noticed the 3 doors per craft thing, but I only really considered wood doors for this.  GT recycling needs to be something in mind when I'm in the configs.  I'm assuming that Malisis Doors is the culprit for changing the recipe.  Should be quite an easy fix.  I have a round of just fixes and tweaks to post once 3.13.1 is actually live (haven't checked if it posted yet), so a fix will be included with that pack of fixes/tweaks towards the end of the week.

**Comment by lazerous42** [comment]
I was mistaken earlier.  It was fixed by deactivating Et Futurum doors module (3 doors per craft is a vanilla change in 1.8+).  It functionally adds nothing as Malisis Doors adds the extra door types.  Deactivating this fixes the dupe and removes confusion.  You can grab the configs from here and all of the fixes/tweaks I have made in the last week week will be posted at the end of the week.
