### ISSUE TITLE
Chromaticraft luminous cliffs biome does not spawn with BOP

### ISSUE THREAD

**Issue by wholesalegerbils** [lazerous42/Ascension-of-the-Technomancer#8]
I'm not sure if it's a biome ID issue or what but in worlds where Biomes O' Plenty is active you cannot find the Luminous Cliffs which is a new biome from Chromaticraft since v17a.  I dumped biome data with NEI and then used Reika's command /findbiome 150 but it didn't detect any Luminous Cliffs biomes within a 65536 radius.  Using this command on other biomes works fine (even areas you haven't generated them yet).  I created 3 fresh BOP worlds to test and was unable to find it each time.  I created a fresh default world without BOP and it found multiple Luminous Cliffs biomes in the area.

Chromaticraft is pretty opaque in terms of progression so I can't determine if Luminous Cliffs are needed for progression or not.

**Comment by hawk767** [comment]
I've tried a couple really simple config changes and have had no luck correcting this so hopefully its not a bigger issue. 

I've disabled some of BOP's biomes, changed the Cliffs id, changed the weight, no luck across the board.

**Comment by lazerous42** [comment]
I know I responded to one of you in a YouTube comment, but I did notice that the frequency was still at 4 (i.e. super rare with a mostly full biome array) for the new biome, and 10 for Rainbow/Ender forest.  I have bumped it up to match, when doing some tweaking during the week, but I haven't really had time to try and hunt for it post change.  This is on the agenda for testing tomorrow night, along with the next round of tweaks (and maybe some new content, but that might have to wait until the next version)

**Comment by lazerous42** [comment]
So after some extensive testing and review of the Chromaticraft codebase, this seems to be a legit cross mod bug (as opposed to a configuration issue) and as such I have submitted the issue on Reika's GitHub for his mods.  You can follow the issue status here

[Chromaticraft/Bimoes O' Plenty Luminous Cliffs Spawn Bug](https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/1540)

Sorry I don't have better news, but this is an issue that will screw up progression (Luma Lotus now grows exclusively in this biome).  At least there is tons of other content to play with in the mean time.  I will of course keep you posted with the progress on this issue.

**Comment by lazerous42** [comment]
Well, I've got some bad news and some bad news.  First, the bad news.  The problem is apparently related to the way this new biome is special in terms of how it interacts with the world generator base class (see linked issue for something vaguely resembling details).  Basically, it doesn't spawn using the normal biome spawning rules and thus will not appear in custom world types (i.e. BIOMESOP, RTG, etc).  Since luma lotus now spawns exclusively in this biome, this cripples progression.  The only option I can see is to revert to an earlier version.  Now this is generally impossible because old versions are removed as soon as the new ones are posted.  

The tiny amount of good news it that I don't just store data in GitHub, I have a private svn server that contains all historical versions of AotT.  Now it's just a matter of if anything truly horrible happens from the roll back.  I'm going to test is out now, in hopes of posting the rollback and the content update (it's not all bad, at least there's a new content update) tomorrow.  Hopefully I can suppress the version update nagware since updating is literally impossible.  Also don't know if an older CC can work with a new DragonAPI (not hopeful, but worth testing)

Oh yes, the other bad news.  My computer crapped into it's proverbial bed Saturday when I had the audacity to plug in a second Xbox controller.  Most functionality has been restored, except for Shadowplay.  So let's playing is on hiatus until I get that sorted out.  That's a problem for another day.

**Comment by lazerous42** [comment]
Or maybe... maybe there is another way.  A way have our rich, delicious, BIOMESOP cake, and eat the DEFAULT one too...

Here's hoping the plan works.

Also, v18 of Reika's mods just dropped between this comment and the last.  We're going to adopt that one a bit slower, provided that we can move forward at all.

**Comment by lazerous42** [comment]
Well good news so far, my plan seems to be functional (at a superficial glance).  The plan I am testing out is to use a mod to create a second overworld that uses the DEFAULT world generator.  This should circumvent the problem.  This will take a few days to test out fully (so far all I have confirmed is that the MultiWorld generator mod doesn't crash the game), but I consider this to be a way better solution.  From what I know of this bug, this solution should work fine.

I believe that all of this unpleasantness stems from doing tricky stuff to prevent luminous cliff from being near world spawn.  Of the >25 generation tests I performed while investigating this issue, lunimous cliffs never appeared closer that 10km from spawn (well, the successful DEFAULT world tests used as a baseline)

**Comment by lazerous42** [comment]
Good news!  The core of my workaround plan is viable, I can indeed use another mod to generate a psudo-overworld dimension that acts as a world type of DEFAULT and the vanilla dimension provider.  So Although there is nothing I can do to get the luminous cliffs to spawn in the overworld, I can get this dimension into the game and fix the broken progression without resorting to back dating Reika's mods.

There is more work yet to be done here, as I need a way to plan out how to access this dimension in the relatively early game.  I might also investigate adding an additional dimension using the RTG dimension provider to give people a choice of the world type they would like to live in.  I have some thoughts on how this can work, but it will take a couple of days of exploration to ensure I make sound choices in this area.  Ultimately, you can expect this fix to drop within a week from now (probably less as I will be working on this heavily over the weekend) along with a new content addon, and update of Reika's mods and a really nice quality of life enhancement (hiding about 200 pages of microblock crap from NEI).

I'll be in touch, thanks for playing/watching

**Comment by hawk767** [comment]
Looking forward to the next update and really digging into this pack. Hopefully will line up with my weekend after this short work week for me.

**Comment by lazerous42** [comment]
Unfortunately I'm not finished yet, but I'm happy to see that people are checking this and getting the updates.  Version 5 is pretty substantial, the new content is about 70% in place.  The way I've settled upon to access the new dimension is going to be through the use of Advanced Rocketry.  This will ultimately be replacing Galacticraft as it is utterly superior to it in every way.  I haven't had any problems with testing out removing GC from the pack on a live world, but I still need to test a few things about this process to ensure it's 100% safe.
In addition to the major content update, there are a few odds and ends additions that are just a little bit of extra flavor and Reika's mods will be updated to 18b.  Lot's of fun stuff, but I have to be sure a change of this size is safe and well tested for deployment.  Quality first.  Just wanted to keep people up to date.

**Comment by lazerous42** [comment]
I figured now would be a good time for an update.  I am now in the production testing stage of the update.  If you are unfamiliar with the developer speak, production testing is generally the review testing of the full product to ensure you didn't catastrophically fuck anything with your enhancements.  All of the unit testing has passed, so things should be in their releasable form now.  I just want to play for a bit before sending this out into the world for consumption.  What a long road it has been to get this setup, but in the end I think that the results really add to the flow of the pack as a whole and make it feel even bigger than it did before.  

Also, do note that there is a warning about the update at the head of the readme on this project page.  Galacticraft and Warp Drive have been cut from the pack, so you really don't want your player hanging out in the dimensions associated with those mods because you will crash.  Galacticraft really adds nothing of consequence when compared to Advanced Rocketry.  Although Warp Drive's warp ship concept was pretty cool, It really needed a lot of configuration for it to provide any real benefit to the pack.  It didn't really seem to be an easy task to configure this mod, and it just wasn't worth the trouble for something that is far less unique in v5.0.1

**Comment by lazerous42** [comment]
Version 5.0.1 has been posted to FTB for review/deployment, so it's in there hands now.  You should see the update in a day or two depending on when they get to it.  You will be able to reach this biome on a planet called the Feyweald.  It's in orbit around a gas giant called Vorpera in your home star system.  It will be "discovered" be default along with the rest of your home system.  All other planets around all other stars will need to be discovered through the research system.

Good luck, and fly safe
